### ISSUE TITLE
Issue with pytorch GPU use 

### ISSUE THREAD

**Issue by raffazizzi** [Living-with-machines/DeezyMatch_tutorials#4]
I followed the instructions to install locally (I used venv + pip), then I ran `python prepare_dirs.py` successfully. But when I get to the first step in the notebook I encounter the issue described here: https://github.com/pytorch/pytorch/issues/31285).

In short, pytorch believes it can use my GPU, but in fact CUDA does not support it and returns and error (`CUDA error: no kernel image is available for execution on the device`).

Following @fedenanni's advice during the workshop, I could work around this by setting  `use_gpu: False` in the YAML files of each tutorial, but a more permanent solution may be needed for future workshops.

**Comment by kasra-hosseini** [comment]
Thanks, @raffazizzi for reporting this. I have created an issue for this on DeezyMatch: https://github.com/Living-with-machines/DeezyMatch/issues/132 and will try to address it in the next release.

**Comment by kallewesterling** [comment]
Closed as the issue looks like it has been transferred to the DeezyMatch repo.
